org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.4.10

mod_id=matteroverdrive
mod_name=Matter Overdrive
mod_license=GPL-3.0-only
mod_version=0.1
mod_group_id=matteroverdrive
mod_authors=MVQ1303
mod_description=Matter Overdrive 0.1 - a Forge 1.20.1 port maintained by MVQ1303.
