pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

gradle.beforeProject { project ->
    if (project.path == ':') {
        project.apply from: new File(settingsDir, 'gradle/sound-verification.gradle')
    }
}

rootProject.name = 'MatterOverdrive-1.20.1-port'
