package matteroverdrive.worldgen;

import com.mojang.serialization.Codec;
import matteroverdrive.entity.RangedRogueAndroidEntity;
import matteroverdrive.registry.ModEntities;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.MobSpawnType;
import net.minecraft.world.level.WorldGenLevel;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.FeaturePlaceContext;
import net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration;

/**
 * Adds the source-backed Android House population rule that existed in 1.12.2:
 * one guaranteed level-3 legendary ranged Rogue Android in addition to the
 * ordinary house defenders generated by the recovered structure layout.
 */
public final class AndroidHouseParityFeature extends Feature<NoneFeatureConfiguration> {
    private final ModernizedStructureFeature delegate;

    public AndroidHouseParityFeature(Codec<NoneFeatureConfiguration> codec) {
        super(codec);
        this.delegate = new ModernizedStructureFeature(codec, LegacyParityStructureFeature.Kind.ANDROID_HOUSE);
    }

    @Override
    public boolean place(FeaturePlaceContext<NoneFeatureConfiguration> context) {
        if (!delegate.place(context)) return false;
        spawnLegendary(context.level(), context.origin().below(2).offset(2, 4, 0), context.random());
        return true;
    }

    private static void spawnLegendary(WorldGenLevel level, BlockPos pos, RandomSource random) {
        if (!level.getWorldBorder().isWithinBounds(pos)) return;
        RangedRogueAndroidEntity android = ModEntities.RANGED_ROGUE_ANDROID.get().create(level.getLevel());
        if (android == null) return;
        android.moveTo(pos.getX() + 0.5D, pos.getY(), pos.getZ() + 0.5D, random.nextFloat() * 360.0F, 0.0F);
        if (!level.noCollision(android)) {
            android.discard();
            return;
        }
        android.finalizeSpawn(level, level.getCurrentDifficultyAt(pos), MobSpawnType.STRUCTURE, null, null);

        // RogueAndroidEntity already persists and reapplies these two source-backed fields.
        CompoundTag rank = new CompoundTag();
        android.addAdditionalSaveData(rank);
        rank.putInt("AndroidLevel", 3);
        rank.putBoolean("Legendary", true);
        android.readAdditionalSaveData(rank);

        android.setPersistenceRequired();
        level.addFreshEntity(android);
    }
}
