package matteroverdrive.item;

import matteroverdrive.quest.ContractStageSupport;
import matteroverdrive.registry.ModItems;
import net.minecraft.ChatFormatting;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.nbt.Tag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;
import net.minecraftforge.registries.ForgeRegistries;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/** Self-contained contract/quest stack with backward compatibility for the early 1.20.1 format. */
public class ContractItem extends Item {
    public static final String TYPE="Type", TARGET="Target", TARGETS="Targets", GOAL="Goal", PROGRESS="Progress", REWARD="Reward", REWARD_COUNT="RewardCount", REWARDS="Rewards", CONTRACT_ID="ContractId", TITLE="Title", XP="Xp", CHILDREN_ONLY="ChildrenOnly";
    public ContractItem(Properties properties) { super(properties.stacksTo(1)); }
    public static ItemStack collect(String itemId,int goal,String rewardId,int rewardCount){return create("custom_collect","Collection Contract","collect",List.of(itemId),goal,0,false,List.of(new RewardSpec(rewardId,rewardCount)));}
    public static ItemStack hunt(String entityId,int goal,String rewardId,int rewardCount){return create("custom_hunt","Hunting Contract","hunt",List.of(entityId),goal,0,false,List.of(new RewardSpec(rewardId,rewardCount)));}
    public static ItemStack create(String id,String title,String type,List<String> targets,int goal,int xp,boolean childrenOnly,List<RewardSpec> rewards){
        ItemStack contract=new ItemStack(ModItems.get("contract").get()); CompoundTag tag=contract.getOrCreateTag(); tag.putString(CONTRACT_ID,id==null?"":id); tag.putString(TITLE,title==null?"Contract":title); tag.putString(TYPE,type==null?"":type); tag.putInt(GOAL,Math.max(1,goal)); tag.putInt(PROGRESS,0); tag.putInt(XP,Math.max(0,xp)); tag.putBoolean(CHILDREN_ONLY,childrenOnly);
        if(targets!=null&&!targets.isEmpty()){tag.putString(TARGET,targets.get(0));ListTag targetTags=new ListTag();for(String target:targets)if(target!=null&&!target.isBlank())targetTags.add(StringTag.valueOf(target));tag.put(TARGETS,targetTags);}
        if(rewards!=null&&!rewards.isEmpty()){RewardSpec first=rewards.get(0);tag.putString(REWARD,first.id());tag.putInt(REWARD_COUNT,Math.max(1,first.count()));ListTag rewardTags=new ListTag();for(RewardSpec reward:rewards){if(reward==null||reward.id()==null||reward.id().isBlank())continue;CompoundTag entry=new CompoundTag();entry.putString("Id",reward.id());entry.putInt("Count",Math.max(1,reward.count()));rewardTags.add(entry);}tag.put(REWARDS,rewardTags);}return contract;}
    public static boolean advancesWithPickup(ItemStack c,ItemStack p){ResourceLocation id=ForgeRegistries.ITEMS.getKey(p.getItem());return "collect".equals(type(c))&&id!=null&&matchesTarget(c,id.toString());}
    public static boolean advancesWithKill(ItemStack c,ResourceLocation e,boolean baby){return "hunt".equals(type(c))&&e!=null&&(!childrenOnly(c)||baby)&&matchesTarget(c,e.toString());}
    public static boolean advancesWithCraft(ItemStack c,ItemStack x){ResourceLocation id=ForgeRegistries.ITEMS.getKey(x.getItem());return "craft".equals(type(c))&&id!=null&&matchesTarget(c,id.toString());}
    public static boolean advancesWithMine(ItemStack c,ResourceLocation b){return "mine".equals(type(c))&&b!=null&&matchesTarget(c,b.toString());}
    public static boolean advancesWithScan(ItemStack c,ResourceLocation b){return "scan".equals(type(c))&&b!=null&&matchesTarget(c,b.toString());}
    public static boolean advancesWithScanName(ItemStack c,String n){if(!"scan".equals(type(c))||n==null||n.isBlank())return false;CompoundTag tag=c.getOrCreateTag();if(tag.contains(TARGETS,Tag.TAG_LIST)){ListTag list=tag.getList(TARGETS,Tag.TAG_STRING);for(int i=0;i<list.size();i++)if(n.equals(displayNameForId(list.getString(i))))return true;}return n.equals(displayNameForId(tag.getString(TARGET)));}
    public static boolean advancesWithTransport(ItemStack c){return "transport".equals(type(c));} public static boolean advancesWithAnomaly(ItemStack c){return "anomaly".equals(type(c));}
    public static boolean matchesTarget(ItemStack c,String id){if(id==null||id.isBlank())return false;CompoundTag tag=c.getOrCreateTag();if(tag.contains(TARGETS,Tag.TAG_LIST)){ListTag list=tag.getList(TARGETS,Tag.TAG_STRING);for(int i=0;i<list.size();i++)if(id.equals(list.getString(i)))return true;}return id.equals(tag.getString(TARGET));}
    public static boolean advanceAndCheck(ItemStack c,int a){boolean before=complete(c);advance(c,a);return !before&&complete(c);} public static void advance(ItemStack c,int a){CompoundTag tag=c.getOrCreateTag();int goal=Math.max(0,tag.getInt(GOAL));tag.putInt(PROGRESS,Math.min(goal,Math.max(0,tag.getInt(PROGRESS))+Math.max(0,a)));}
    public static boolean complete(ItemStack c){CompoundTag tag=c.getOrCreateTag();return tag.getInt(GOAL)>0&&tag.getInt(PROGRESS)>=tag.getInt(GOAL);} public static int progress(ItemStack c){return Math.max(0,c.getOrCreateTag().getInt(PROGRESS));} public static int goal(ItemStack c){return Math.max(1,c.getOrCreateTag().getInt(GOAL));} public static int xp(ItemStack c){return Math.max(0,c.getOrCreateTag().getInt(XP));} public static String type(ItemStack c){return c.getOrCreateTag().getString(TYPE);} public static String contractId(ItemStack c){return c.getOrCreateTag().getString(CONTRACT_ID);} public static boolean childrenOnly(ItemStack c){return c.getOrCreateTag().getBoolean(CHILDREN_ONLY);} public static String title(ItemStack c){String t=c.getOrCreateTag().getString(TITLE);return t.isBlank()?"Contract":t;}
    public static ItemStack reward(ItemStack c){List<ItemStack> r=rewardItems(c);return r.isEmpty()?ItemStack.EMPTY:r.get(0);} public static List<ItemStack> rewardItems(ItemStack c){CompoundTag tag=c.getOrCreateTag();List<ItemStack> result=new ArrayList<>();if(tag.contains(REWARDS,Tag.TAG_LIST)){ListTag list=tag.getList(REWARDS,Tag.TAG_COMPOUND);for(int i=0;i<list.size();i++){CompoundTag e=list.getCompound(i);ItemStack s=stack(e.getString("Id"),e.getInt("Count"));if(!s.isEmpty())result.add(s);}}if(result.isEmpty()&&tag.contains(REWARD,Tag.TAG_STRING)){ItemStack s=stack(tag.getString(REWARD),tag.getInt(REWARD_COUNT));if(!s.isEmpty())result.add(s);}return Collections.unmodifiableList(result);} private static ItemStack stack(String id,int count){ResourceLocation key=ResourceLocation.tryParse(id);if(key==null)return ItemStack.EMPTY;Item item=ForgeRegistries.ITEMS.getValue(key);return item==null?ItemStack.EMPTY:new ItemStack(item,Math.max(1,count));}
    @Override public boolean isFoil(ItemStack stack){return complete(stack);}
    @Override public void appendHoverText(ItemStack stack,@Nullable Level level,List<Component> tooltip,TooltipFlag flag){tooltip.add(Component.literal(title(stack)).withStyle(ChatFormatting.AQUA));String stage=ContractStageSupport.stageLabel(stack);if(!stage.isBlank())tooltip.add(Component.literal(stage).withStyle(ChatFormatting.LIGHT_PURPLE));tooltip.add(Component.literal(objectiveText(stack)).withStyle(ChatFormatting.GRAY));tooltip.add(Component.literal("Progress: "+progress(stack)+" / "+goal(stack)).withStyle(complete(stack)?ChatFormatting.GREEN:ChatFormatting.WHITE));List<ItemStack> rewards=rewardItems(stack);if(!rewards.isEmpty()){StringBuilder line=new StringBuilder("Rewards: ");for(int i=0;i<rewards.size();i++){if(i>0)line.append(", ");ItemStack r=rewards.get(i);line.append(r.getCount()).append('x').append(' ').append(r.getHoverName().getString());}tooltip.add(Component.literal(line.toString()).withStyle(ChatFormatting.GOLD));}if(xp(stack)>0)tooltip.add(Component.literal("Experience: "+xp(stack)+" XP").withStyle(ChatFormatting.YELLOW));tooltip.add(Component.literal(complete(stack)?"Return to the quest giver or Contract Market to redeem.":"Keep this contract in your inventory to track progress.").withStyle(ChatFormatting.DARK_GRAY));}
    public static String objectiveText(ItemStack stack){String target=primaryTargetName(stack);String required=ContractStageSupport.requiredName(stack);return switch(type(stack)){case "hunt"->childrenOnly(stack)?"Eliminate juvenile targets":"Eliminate "+target;case "collect"->"Collect "+target;case "craft"->"Craft "+target;case "mine"->"Mine "+target;case "scan"->"Scan "+target;case "transport"->"Use a Matter Overdrive Transporter";case "anomaly"->"Enter a gravitational anomaly event horizon";case "place"->"Place "+target;case "block_interact"->"Interact with "+target;case "item_interact"->required.isBlank()?"Use "+target:"Use "+required;case "item_interact_consume"->required.isBlank()?"Read/use "+target:"Read/use "+required;case "conversation"->"Talk to "+target;default->"Complete the assigned objective";};}
    private static String primaryTargetName(ItemStack s){return displayNameForId(s.getOrCreateTag().getString(TARGET));} private static String displayNameForId(String id){ResourceLocation key=ResourceLocation.tryParse(id);if(key==null)return id;Item item=ForgeRegistries.ITEMS.getValue(key);if(item!=null&&item!=net.minecraft.world.item.Items.AIR)return new ItemStack(item).getHoverName().getString();var block=ForgeRegistries.BLOCKS.getValue(key);if(block!=null&&block!=net.minecraft.world.level.block.Blocks.AIR)return new ItemStack(block.asItem()).getHoverName().getString();return key.getPath().replace('_',' ');} public record RewardSpec(String id,int count){}
}
