package matteroverdrive.menu;
import matteroverdrive.blockentity.TransporterBlockEntity;import matteroverdrive.item.MachineUpgradeItem;import matteroverdrive.registry.ModBlocks;import matteroverdrive.registry.ModMenus;import net.minecraft.core.BlockPos;import net.minecraft.network.FriendlyByteBuf;import net.minecraft.world.entity.player.Inventory;import net.minecraft.world.entity.player.Player;import net.minecraft.world.inventory.*;import net.minecraft.world.item.ItemStack;import net.minecraft.world.level.block.entity.BlockEntity;import net.minecraftforge.common.capabilities.ForgeCapabilities;import net.minecraftforge.items.SlotItemHandler;
public class TransporterMenu extends AbstractContainerMenu{private static final int M=7,PS=7,PE=34,H=43;private final TransporterBlockEntity t;private final ContainerData d;public TransporterMenu(int id,Inventory i,FriendlyByteBuf b){this(id,i,get(i,b.readBlockPos()),new SimpleContainerData(12));}public TransporterMenu(int id,Inventory i,TransporterBlockEntity t){this(id,i,t,t.getData());}private TransporterMenu(int id,Inventory i,TransporterBlockEntity t,ContainerData d){super(ModMenus.TRANSPORTER.get(),id);this.t=t;this.d=d;addSlot(new SlotItemHandler(t.getItemHandler(),0,44,44));addSlot(new SlotItemHandler(t.getItemHandler(),1,112,44));for(int s=0;s<5;s++)addSlot(new SlotItemHandler(t.getUpgrades(),s,43+s*18,78));for(int r=0;r<3;r++)for(int c=0;c<9;c++)addSlot(new Slot(i,c+r*9+9,8+c*18,145+r*18));for(int c=0;c<9;c++)addSlot(new Slot(i,c,8+c*18,203));addDataSlots(d);}private static TransporterBlockEntity get(Inventory i,BlockPos p){BlockEntity b=i.player.level().getBlockEntity(p);if(b instanceof TransporterBlockEntity t)return t;throw new IllegalStateException("Transporter missing");}@Override public ItemStack quickMoveStack(Player p,int x){Slot s=slots.get(x);if(!s.hasItem())return ItemStack.EMPTY;ItemStack a=s.getItem(),z=a.copy();boolean ok;if(x<M)ok=moveItemStackTo(a,PS,H,true);else{ok=false;if(a.getItem() instanceof MachineUpgradeItem)ok=moveItemStackTo(a,2,M,false);if(!ok&&t.getItemHandler().isItemValid(0,a))ok=moveItemStackTo(a,0,1,false);if(!ok&&a.getCapability(ForgeCapabilities.ENERGY).map(e->e.canExtract()).orElse(false))ok=moveItemStackTo(a,1,2,false);if(!ok)ok=x<PE?moveItemStackTo(a,PE,H,false):moveItemStackTo(a,PS,PE,false);}if(!ok)return ItemStack.EMPTY;if(a.isEmpty())s.set(ItemStack.EMPTY);else s.setChanged();s.onTake(p,a);return z;}@Override public boolean stillValid(Player p){return stillValid(ContainerLevelAccess.create(t.getLevel(),t.getBlockPos()),p,ModBlocks.get("transporter").get());}public int progress(){return d.get(0);}public int cycle(){return d.get(1);}public int e(){return both(2,3);}public int cap(){return both(4,5);}public boolean target(){return d.get(6)!=0;}public int dist(){return d.get(7);}public int cost(){return d.get(8);}public int range(){return d.get(9);}public int cooldown(){return d.get(10);}public boolean running(){return d.get(11)!=0;}private int both(int l,int h){return(d.get(l)&65535)|((d.get(h)&65535)<<16);}
    @Override
    public boolean clickMenuButton(Player player, int id) {
        if (id != 1) return false;
        boolean enabled = t.getEnergy().toggleInfiniteEnergy();
        player.displayClientMessage(net.minecraft.network.chat.Component.literal(
                "[DEBUG] Infinite energy: " + (enabled ? "ON" : "OFF")), true);
        return true;
    }
}
