package matteroverdrive.client.screen;

import matteroverdrive.menu.DecomposerMenu;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.network.chat.Component;
import net.minecraft.world.entity.player.Inventory;
import java.util.Locale;

public class DecomposerScreen extends AbstractContainerScreen<DecomposerMenu> {
    private static final String[] PAGES={"HOME","TASKS","CONFIG","UPGRADES"};private int page;
    public DecomposerScreen(DecomposerMenu menu,Inventory playerInventory,Component title){super(menu,playerInventory,title);imageWidth=330;imageHeight=196;inventoryLabelY=103;}
    @Override protected void init(){super.init();rebuildButtons();}
    private void rebuildButtons(){clearWidgets();for(int i=0;i<PAGES.length;i++){final int target=i;Button tab=Button.builder(Component.literal(PAGES[i]),b->{page=target;rebuildButtons();}).bounds(leftPos+178+i*36,topPos+28,34,15).build();tab.active=page!=i;addRenderableWidget(tab);}addRenderableWidget(Button.builder(Component.literal("INF FE"),b->{if(minecraft!=null&&minecraft.gameMode!=null)minecraft.gameMode.handleInventoryButtonClick(menu.containerId,1);}).bounds(leftPos+imageWidth-57,topPos+5,52,16).build());if(page==2)addRenderableWidget(Button.builder(Component.literal("CYCLE RS"),b->{if(minecraft!=null&&minecraft.gameMode!=null)minecraft.gameMode.handleInventoryButtonClick(menu.containerId,2);}).bounds(leftPos+218,topPos+71,76,16).build());}
    @Override public void render(GuiGraphics g,int mx,int my,float pt){renderBackground(g);super.render(g,mx,my,pt);renderTooltip(g,mx,my);}
    @Override protected void renderBg(GuiGraphics g,float pt,int mx,int my){int x=leftPos,y=topPos;MachineScreenStyle.drawFrame(g,x,y,imageWidth,imageHeight,inventoryLabelY,MachineScreenStyle.CYAN);MachineScreenStyle.drawSection(g,x+17,y+32,142,62);MachineScreenStyle.drawSection(g,x+170,y+25,151,162);MachineScreenStyle.drawSlot(g,x+25,y+43);MachineScreenStyle.drawSlot(g,x+79,y+43);MachineScreenStyle.drawSlot(g,x+133,y+43);for(int s=0;s<4;s++)MachineScreenStyle.drawSlot(g,x+52+s*18,y+79);MachineScreenStyle.drawLegacyProgressArrow(g,x+50,y+44,menu.getProgress(),menu.getMaxProgress());MachineScreenStyle.drawLegacyEnergyMeter(g,x+6,y+30,menu.getEnergy(),menu.getEnergyCapacity());MachineScreenStyle.drawLegacyMatterMeter(g,x+154,y+30,menu.getMatter(),menu.getMatterCapacity());}
    @Override protected void renderLabels(GuiGraphics g,int mx,int my){g.drawString(font,title,8,9,MachineScreenStyle.TEXT,false);g.drawString(font,playerInventoryTitle,8,inventoryLabelY,MachineScreenStyle.MUTED,false);g.drawString(font,menu.getEnergy()+" / "+menu.getEnergyCapacity()+" FE",18,29,MachineScreenStyle.MUTED,false);g.drawString(font,menu.getMatter()+" / "+menu.getMatterCapacity()+" kM",18,70,MachineScreenStyle.MUTED,false);int input=menu.getInputMatterValue();if(input>0)g.drawString(font,input+" kM | "+menu.getEnergyPerTick()+" FE/t",48,58,MachineScreenStyle.TEXT,false);g.drawString(font,String.format(Locale.ROOT,"Failure %.4f%%",menu.getFailureChancePercent()),48,68,MachineScreenStyle.DANGER,false);switch(page){case 1->renderTasks(g);case 2->renderConfig(g);case 3->renderUpgrades(g);default->renderHome(g);}}
    private void renderHome(GuiGraphics g){g.drawString(font,"DECOMPOSITION",207,51,MachineScreenStyle.CYAN,false);g.drawString(font,"Energy "+menu.getEnergy()+" / "+menu.getEnergyCapacity(),184,71,MachineScreenStyle.TEXT,false);g.drawString(font,"Matter "+menu.getMatter()+" / "+menu.getMatterCapacity(),184,86,MachineScreenStyle.BLUE,false);g.drawString(font,"Input value "+menu.getInputMatterValue()+" kM",184,101,menu.getInputMatterValue()>0?MachineScreenStyle.GREEN:MachineScreenStyle.MUTED,false);g.drawString(font,"Consumption "+menu.getEnergyPerTick()+" FE/t",184,116,MachineScreenStyle.CYAN,false);g.drawString(font,String.format(Locale.ROOT,"Failure %.4f%%",menu.getFailureChancePercent()),184,131,MachineScreenStyle.DANGER,false);g.drawString(font,"Physical IO + 4 upgrades left",184,151,MachineScreenStyle.MUTED,false);}
    private void renderTasks(GuiGraphics g){int max=Math.max(1,menu.getMaxProgress()),pct=Math.min(100,menu.getProgress()*100/max);g.drawString(font,"ACTIVE TASK",213,51,MachineScreenStyle.CYAN,false);g.drawString(font,menu.getInputMatterValue()>0?"Input recognized":"Waiting for valid input",184,72,menu.getInputMatterValue()>0?MachineScreenStyle.GREEN:MachineScreenStyle.AMBER,false);g.drawString(font,"Progress "+pct+"%",184,88,pct>0?MachineScreenStyle.GREEN:MachineScreenStyle.MUTED,false);g.drawString(font,"Cycle "+menu.getProgress()+" / "+menu.getMaxProgress()+" t",184,103,MachineScreenStyle.TEXT,false);g.drawString(font,"Matter yield "+menu.getInputMatterValue()+" kM",184,118,MachineScreenStyle.BLUE,false);g.drawString(font,"Energy demand "+menu.getEnergyPerTick()+" FE/t",184,133,MachineScreenStyle.CYAN,false);}
    private void renderConfig(GuiGraphics g){g.drawString(font,"CONFIGURATION",204,51,MachineScreenStyle.CYAN,false);g.drawString(font,"Redstone: "+menu.getRedstoneModeLabel(),184,64,MachineScreenStyle.CYAN,false);g.drawString(font,"LOW = work without signal",184,94,MachineScreenStyle.MUTED,false);g.drawString(font,"HIGH = work with signal",184,108,MachineScreenStyle.MUTED,false);g.drawString(font,"DISABLED = ignore signal",184,122,MachineScreenStyle.MUTED,false);g.drawString(font,"Charging/output stay live",184,144,MachineScreenStyle.GREEN,false);}
    private void renderUpgrades(GuiGraphics g){g.drawString(font,"UPGRADES",220,51,MachineScreenStyle.CYAN,false);g.drawString(font,"4 physical upgrade slots",184,72,MachineScreenStyle.TEXT,false);g.drawString(font,"Speed: cycle throughput",184,90,MachineScreenStyle.MUTED,false);g.drawString(font,"Power: FE efficiency",184,105,MachineScreenStyle.MUTED,false);g.drawString(font,"Matter: storage/handling",184,120,MachineScreenStyle.MUTED,false);g.drawString(font,"Slots remain usable on all pages",184,145,MachineScreenStyle.CYAN,false);}
}
