package matteroverdrive.client.screen;

import matteroverdrive.menu.MatterRecyclerMenu;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.network.chat.Component;
import net.minecraft.world.entity.player.Inventory;
import java.util.Locale;

public class MatterRecyclerScreen extends AbstractContainerScreen<MatterRecyclerMenu> {
    private static final String[] PAGES={"HOME","TASKS","CONFIG","UPGRADES"};private int page;
    public MatterRecyclerScreen(MatterRecyclerMenu menu,Inventory inventory,Component title){super(menu,inventory,title);imageWidth=330;imageHeight=184;inventoryLabelY=91;}
    @Override protected void init(){super.init();rebuildButtons();}
    private void rebuildButtons(){clearWidgets();for(int i=0;i<PAGES.length;i++){final int target=i;Button tab=Button.builder(Component.literal(PAGES[i]),b->{page=target;rebuildButtons();}).bounds(leftPos+178+i*36,topPos+29,34,15).build();tab.active=page!=i;addRenderableWidget(tab);}if(page==0)addRenderableWidget(Button.builder(Component.literal("INF FE"),b->{if(minecraft!=null&&minecraft.gameMode!=null)minecraft.gameMode.handleInventoryButtonClick(menu.containerId,1);}).bounds(leftPos+257,topPos+70,56,16).build());if(page==2)addRenderableWidget(Button.builder(Component.literal("CYCLE RS"),b->{if(minecraft!=null&&minecraft.gameMode!=null)minecraft.gameMode.handleInventoryButtonClick(menu.containerId,2);}).bounds(leftPos+218,topPos+70,76,16).build());}
    @Override public void render(GuiGraphics g,int mx,int my,float pt){renderBackground(g);super.render(g,mx,my,pt);renderTooltip(g,mx,my);}
    @Override protected void renderBg(GuiGraphics g,float pt,int mx,int my){int x=leftPos,y=topPos;MachineScreenStyle.drawFrame(g,x,y,imageWidth,imageHeight,inventoryLabelY,MachineScreenStyle.GREEN);MachineScreenStyle.drawSection(g,x+17,y+32,142,54);MachineScreenStyle.drawSection(g,x+176,y+25,145,65);MachineScreenStyle.drawSlot(g,x+25,y+43);MachineScreenStyle.drawSlot(g,x+79,y+43);MachineScreenStyle.drawSlot(g,x+133,y+43);for(int s=0;s<4;s++)MachineScreenStyle.drawSlot(g,x+52+s*18,y+65);MachineScreenStyle.drawHorizontalBar(g,x+48,y+48,43,6,menu.getProgress(),menu.getMaxProgress(),MachineScreenStyle.GREEN);MachineScreenStyle.drawVerticalBar(g,x+8,y+30,7,40,menu.getEnergy(),menu.getEnergyCapacity(),MachineScreenStyle.RED);}
    @Override protected void renderLabels(GuiGraphics g,int mx,int my){g.drawString(font,title,8,9,MachineScreenStyle.TEXT,false);g.drawString(font,playerInventoryTitle,8,inventoryLabelY,MachineScreenStyle.MUTED,false);g.drawString(font,menu.getEnergy()+" / "+menu.getEnergyCapacity()+" FE",18,29,MachineScreenStyle.MUTED,false);g.drawString(font,menu.getMatter()>0?menu.getMatter()+" kM":"Waiting for recyclable input",48,56,menu.getMatter()>0?MachineScreenStyle.GREEN:MachineScreenStyle.MUTED,false);switch(page){case 1->renderTasks(g);case 2->renderConfig(g);case 3->renderUpgrades(g);default->renderHome(g);}}
    private void renderHome(GuiGraphics g){boolean active=menu.getMatter()>0&&menu.getProgress()>0;g.drawString(font,"RECYCLER STATUS",204,51,MachineScreenStyle.GREEN,false);g.drawString(font,active?"RECYCLING":"IDLE",188,64,active?MachineScreenStyle.GREEN:MachineScreenStyle.MUTED,false);g.drawString(font,"Matter yield "+menu.getMatter()+" kM",188,76,MachineScreenStyle.TEXT,false);g.drawString(font,"Demand "+menu.getEnergyPerTick()+" FE/t",188,87,MachineScreenStyle.CYAN,false);}
    private void renderTasks(GuiGraphics g){int max=Math.max(1,menu.getMaxProgress()),progress=Math.min(max,Math.max(0,menu.getProgress())),percent=progress*100/max;g.drawString(font,"RECYCLING TASK",202,51,MachineScreenStyle.GREEN,false);g.drawString(font,"Progress "+percent+"%",188,64,MachineScreenStyle.TEXT,false);g.drawString(font,"Cycle "+progress+" / "+max+" t",188,75,MachineScreenStyle.TEXT,false);g.drawString(font,String.format(Locale.ROOT,"Duration %.2f s",max/20.0D),188,86,MachineScreenStyle.MUTED,false);g.drawString(font,"Yield "+menu.getMatter()+" kM | "+menu.getEnergyPerTick()+" FE/t",188,97,MachineScreenStyle.CYAN,false);}
    private void renderConfig(GuiGraphics g){g.drawString(font,"CONFIGURATION",204,51,MachineScreenStyle.GREEN,false);g.drawString(font,"Redstone: "+menu.getRedstoneModeLabel(),188,62,MachineScreenStyle.CYAN,false);g.drawString(font,"LOW = run without signal",188,88,MachineScreenStyle.MUTED,false);g.drawString(font,"HIGH = run with signal",188,99,MachineScreenStyle.MUTED,false);g.drawString(font,"DISABLED = ignore signal",188,110,MachineScreenStyle.MUTED,false);}
    private void renderUpgrades(GuiGraphics g){g.drawString(font,"UPGRADES",219,51,MachineScreenStyle.GREEN,false);g.drawString(font,"4 physical slots shown left",188,64,MachineScreenStyle.TEXT,false);g.drawString(font,"Installed machine upgrades",188,76,MachineScreenStyle.MUTED,false);g.drawString(font,"modify the live recycle cycle",188,87,MachineScreenStyle.MUTED,false);g.drawString(font,"and FE demand backend.",188,98,MachineScreenStyle.MUTED,false);}
}
